server:
  port: 8071
voiceMonkey:
  fan:
    turnOnOrOff: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=turn-on-fan-monkey&announcement=test
  entertainment:
    turnOff: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=turn-off-entertainment&announcement=turn off tv
    turnOn: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=turn-on-entertainment-1&announcement=turn on tv
    play: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=play-tv-monkey&announcement=play tv
    pause: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=pause-tv-monkey&announcement=pause tv
  tellTime: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=tell-time&announcement=test
  tellDate: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=tell-date&announcement=test
  drinkWater: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=monkey-announcement&announcement=Drink water please
  hariAnnouncement: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=monkey-announcement-for-hari&announcement=
  hallAnnouncement: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=monkeyannouncementforhall&announcement=
  turnOnDecoLight: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=turn-on-deco-light-monkey&announcement=n
  turnOffDecoLight: https://api.voicemonkey.io/trigger?access_token=aefdfde159807039f4c21fa0a5fe3680&secret_token=811ba0df7e31c018095aa378843aceb5&monkey=turn-off-deco-light-monkey&announcement=f

app:
  bvirtuoso:
    turnOffTv: http://www.bvirtuoso.com/tvOff
    turnOnTv: http://www.bvirtuoso.com/tvOn
    onOffDuration: http://bvirtuoso.herokuapp.com/tvOnOrOffDuration
    getPeopleInfo: http://www.bvirtuoso.com/getPeopleInfo
    getDishInfo: http://www.bvirtuoso.com/getDishInfo
    clearDishAndPeopleInfo: http://www.bvirtuoso.com/clearDishAndPeopleInfo
    harshaAvailability: http://www.bvirtuoso.com/getHarshaAvailability
logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:h2:file:./data/healthInfo
    username: healthInfo
    password: myHealthInfo
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  #    To load the data
  #  sql:
  #    init:
  #      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
